services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports: ["5432:5432"]
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./apps/api/db/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d mydatabase"]
      interval: 5s
      timeout: 3s
      retries: 10

  api:
    build: ./apps/api
    container_name: api
    command: npm run dev
    ports:
      - "4000:4000"
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
    environment:
      PORT: 4000
      DATABASE_URL: postgres://user:password@db:5432/mydatabase
      NODE_ENV: development
      FRONTEND_ORIGIN: http://localhost:5173
      JWT_ACCESS_SECRET: dev-access
      JWT_REFRESH_SECRET: dev-refresh
      ACCESS_TTL: 15m
      REFRESH_TTL: 7d
      COOKIE_DOMAIN: localhost
    volumes:
      - ./apps/api:/occ/app/api
      - /occ/app/api/node_modules
    develop:
      watch:
        - action: sync+restart
          path: ./apps/api
          target: /occ/app/api
    

  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    container_name: web
    environment:
      NODE_ENV: development
      VITE_API_URL: http://localhost:4000
    depends_on:
      - api
    ports:
      - "5173:5173"
    volumes:
      - ./apps/web:/occ/app/web
      - /occ/app/web/node_modules
    develop:
      watch:
        - action: sync
          path: ./apps/web
          target: /occ/app/web
volumes:
  db_data: