== ## 2. Architecture constraints

Constraints represent the limitations and restrictions that influence the design and implementation of Meshed. These constraints are essential to consider during the architectural decision-making process to ensure that the final solution aligns with the project requirements and constraints.

The design of Meshed must adhere to several prototype requirements, quality attribute requirements, and assignment specific specifications.

Senior design non-negotiables that shape the design space.

[cols="1,1,2,2,1"]
|===
| Constraint | Type | Rationale | Impact on design | Reference

| Minimum viable product complete by April 2nd.
| Deadline
| Senior design symposium is on this date.
| Timing, scope, testing.
| 

| CI/CD pipeline must be implemented.
| Technical
| SWE requirement
| Time, testing, tickets, implementation.
| 

| Unit and integration tests must be implemented.
| Technical
| SWE requirement
| Time, testing, tickets, implementation.
| 

| Architectural, design, engineering decisions must be justifiable through engineering analysis.
| Process
| Engineering requirement
| Decision process, implementation, code time, documentation, testing.
| 

|===

### Prototype Requirements

- Optimization Algorithm: Automatic generation of recommended practice times for Coaches to review and select from.
- Conflict Report: A report of all conflicting facility requests for Administrators to review.
- Facility Booking: Coaches submit facility booking requests for the semester or year.
- Centralized Schedule: User-friendly interface for a centralized athletic and academic student schedule.
- Notifications: Alerts for student-athletes when athletic schedule updates.

### Quality Attribute Requirements

- Scalability: Dynamic scaling to handle varying numbers of teams.
- Cost Efficiency: Optimizing resource usage with cloud technologies to minimize expenses.
- Usability: Ensuring simple user-friendly interfaces and features throughout the system.
- Performance: Ensure quick response times when uploading and generating schedules.

### Additional Constraints
- Cost: Cloud hosting cost must remain < $5.00 per team / month
- Regulatory and Compliance: PIPEDA, GSA Group / ISO 27001​, Youth Data Protection data-privacy requirements, language Accessibility Compliance
- Technology standards: Accept .ics, .xlsx and  .csv files, use secure APIs for data exchange