name: Test CI

on:
  push:
  pull_request:

jobs:
  test-ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install Dependancies
        run: npm ci
      - name: Linter
        run: npx turbo run lint     
        env:
          PORT:4000
          FRONTEND_ORIGIN:http://localhost:5173
          JWT_ACCESS_SECRET:"NQE-c6_RJRMYQOFjxBU-4QKiWn6U1ecSIQ1X_uXbMsXVZsJB5XvgSblD9XgkY9dKpVOH9fNLLt2f3VrQlvEFvA=="
          JWT_REFRESH_SECRET:"daTnDEdmIoQLRUYmWqxre0cxjmSSQIrvBfLfy-GWXIlsPS_wLSnRRWPgHTBokWkqiyZodny9V3yuQrINXpVCfA=="
          DATABASE_URL:postgres://user:password@db:5432/mydatabase
          ACCESS_TTL:15m
          REFRESH_TTL:7d
          COOKIE_DOMAIN=localhost
          NODE_ENV:development
          GMAIL_APP_EMAIL:"unitematchalign@gmail.com"
          GMAIL_APP_PASSWORD:"xkij gzin lecn zawb"
      #- run: npm run build --if-present
      - name: Backend Tests
        run: npx turbo run test
      #- run: npm test